[project]
name = "rattler-build-conda-compat"
version = "0.0.5"
description = "A package for exposing rattler-build API for conda-smithy"
authors = ["nichmor <nmorkotilo@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

build_sdist = "pixi run python -m build --sdist"

[dependencies]
python = ">=3.8"
build = "*"
rattler-build = "*"
conda-build = "*"
"ruamel.yaml" = "*"
conda = ">=4.2"
pygithub = ">=2,<3"
tomli = "*"

[pypi-dependencies]
rattler-build-conda-compat = { path = ".", editable = true}


[feature.test.dependencies]
pytest = "*"
syrupy = "*"
ruff = "*"

[feature.test.tasks]
test = "pytest"
snapshot_update = "pytest --snapshot-update"


[environments]
test = ["test"]