[build-system]
requires = [
    "setuptools>=45",
]
build-backend = "setuptools.build_meta"

[project]
name = "rattler-build-conda-compat"
description="A package for exposing rattler-build API for conda-smithy"
version = "0.0.6"
readme = "README.md"
authors = [{name = "Nichita Morcotilo", email = "nichita@prefix.dev"}]
license = {file = "LICENSE.txt"}

requires-python = ">=3.8"
