# name: Run updater that will check for conda-forge packages

on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - uses: prefix-dev/setup-pixi@v0.5.1
          with:
            pixi-version: "latest"

        - name: pixi install
          run: |
           pixi install

        - name: run tests
          run: |
           pixi run -e test pytest
